import React from "react";
import { Text as NativeText } from "react-native";
import { useLocale } from "../context/LocaleContext";

// This compatibility wrapper localizes existing literal <Text> children while
// deliberately leaving unknown values (including business-owned data) unchanged.
//
// HOW TO ADD A NEW STRING:
// 1. Add the exact English phrase as a key under BOTH mr and hi below.
// 2. Use it either as <LocalizedText>Exact Phrase</LocalizedText> (native/RN)
//    or localizeText("Exact Phrase", language) (web / plain JS strings).
// 3. Never build the final string with a number/variable baked in before
//    calling localizeText — translate the static part and concatenate the
//    variable separately, e.g. `${localizeText("Table", language)} ${num}`.
//
// In dev mode, any string rendered in mr/hi that has no dictionary entry
// gets logged to the console once, so missing coverage is easy to find:
// switch the app to Marathi/Hindi, click through every screen, and read
// the console for "[i18n] missing ..." warnings.

const phrases = {
  mr: {
    // ── Nav / shell ─────────────────────────────────────────────────────
    "Dashboard": "डॅशबोर्ड", "Orders": "ऑर्डर", "Menu": "मेनू", "Tables": "टेबल", "Rooms": "रूम", "Analytics": "विश्लेषण", "Expenses": "खर्च", "Inventory": "स्टॉक", "Staff": "कर्मचारी", "Profile": "प्रोफाइल", "Support": "मदत", "Reviews": "पुनरावलोकने", "Referrals": "रेफरल", "Manual": "मॅन्युअल", "Voice": "व्हॉइस", "Servon Assistant": "सर्व्हॉन सहाय्यक", "TABLE": "टेबल", "ADD ITEMS": "पदार्थ जोडा", "Search menu items...": "मेनूमधील पदार्थ शोधा...", "Type a dish name to search your menu.": "मेनूमध्ये शोधण्यासाठी पदार्थाचे नाव टाइप करा.", "Speak your order or room details": "तुमची ऑर्डर किंवा रूमचा तपशील बोला", "Listening…": "ऐकत आहे…", "Understanding…": "समजून घेत आहे…", "Start Recording": "रेकॉर्डिंग सुरू करा", "Stop": "थांबा",
    "Save": "जतन करा", "Cancel": "रद्द करा", "Delete": "हटवा", "Edit": "बदला", "Close": "बंद करा", "Search": "शोधा", "Loading...": "लोड होत आहे...", "Available": "उपलब्ध", "Not Available": "उपलब्ध नाही", "Accept": "स्वीकारा", "Reject": "नकार द्या", "Serve": "सर्व्ह करा", "Print": "प्रिंट करा", "Back": "मागे", "Continue": "पुढे चला", "Confirm": "पुष्टी करा",
    "Add Item": "पदार्थ जोडा", "Add Table": "टेबल जोडा", "Add Room": "रूम जोडा", "Add Stock": "स्टॉक जोडा", "Add New Stock Item": "नवीन स्टॉक पदार्थ जोडा", "Create Order": "ऑर्डर तयार करा", "Room Management": "रूम व्यवस्थापन", "Staff Management": "कर्मचारी व्यवस्थापन", "AI Business Advisor": "AI व्यवसाय सल्लागार", "Live Orders": "चालू ऑर्डर", "Notifications": "सूचना", "Subtotal": "उपएकूण", "Grand Total": "एकूण रक्कम", "Total Amount": "एकूण रक्कम", "Price": "किंमत", "Quantity": "प्रमाण", "Category": "श्रेणी", "Item Name *": "पदार्थाचे नाव *", "Item Name": "पदार्थाचे नाव", "Room Number": "रूम नंबर", "Total Guests": "एकूण पाहुणे", "Male": "पुरुष", "Female": "महिला", "Children": "मुले", "Check In": "चेक इन", "Check Out": "चेक आउट", "Low Stock": "कमी स्टॉक", "Yes, Delete": "होय, हटवा", "Done": "पूर्ण", "Thali": "थाळी",
    "Good morning": "शुभ प्रभात", "Good afternoon": "शुभ दुपार", "Good evening": "शुभ संध्याकाळ", "Good morning 👋": "शुभ प्रभात 👋", "Refresh": "रीफ्रेश", "Orders Today": "आजच्या ऑर्डर", "Revenue Today": "आजची कमाई", "Active Tables": "चालू टेबल", "Top Item": "लोकप्रिय पदार्थ", "No active orders right now": "सध्या कोणतीही चालू ऑर्डर नाही", "Waiting for customers to scan QR": "ग्राहक QR स्कॅन करण्याची वाट पाहत आहे", "Generate Summary": "सारांश तयार करा", "Sales Overview": "विक्रीचा आढावा", "Top Items": "लोकप्रिय पदार्थ", "View all": "सर्व पहा", "Day": "दिवस", "Week": "आठवडा", "Month": "महिना", "Performance Overview": "कामगिरीचा आढावा", "Total Sales": "एकूण विक्री", "Avg. Order Value": "सरासरी ऑर्डर मूल्य", "Tables Occupied": "व्यस्त टेबल", "vs yesterday": "कालच्या तुलनेत", "Live": "चालू", "+ Add Item": "+ पदार्थ जोडा",
    "All": "सर्व", "Starters": "स्टार्टर्स", "Main Course": "मुख्य पदार्थ", "Breads": "पोळ्या", "Rice & Biryani": "भात आणि बिर्याणी", "Desserts": "गोड पदार्थ", "Beverages": "पेय", "Soups": "सूप", "Salads": "सॅलड", "Snacks": "नाश्ता", "Specials": "विशेष", "Your menu is empty": "तुमचा मेनू रिकामा आहे", "Add your first dish and let customers start ordering in minutes.": "तुमचा पहिला पदार्थ जोडा आणि ग्राहकांना ऑर्डर करू द्या.", "Add Your First Item": "तुमचा पहिला पदार्थ जोडा", "Edit Item": "पदार्थ बदला", "This is a Thali / Combo": "ही थाळी / कॉम्बो आहे", "Bundle multiple items under one price": "एका किमतीत अनेक पदार्थ जोडा", "Included Items": "समाविष्ट पदार्थ", "Add Extra (Manual)": "अतिरिक्त पदार्थ जोडा", "Item Image": "पदार्थाचा फोटो", "Tap to upload": "अपलोड करण्यासाठी टॅप करा", "Pick Thali Items": "थाळीचे पदार्थ निवडा",

    // ── Subscription / Profile screen ───────────────────────────────────
    "Subscription": "सदस्यता", "Manage your plan and billing": "तुमचा प्लॅन आणि बिलिंग व्यवस्थापित करा", "Choose Your Plan": "तुमचा प्लॅन निवडा", "Current Plan": "सध्याचा प्लॅन", "Best Value": "सर्वोत्तम मूल्य", "⭐ Best Value": "⭐ सर्वोत्तम मूल्य", "Monthly": "मासिक", "Quarterly": "त्रैमासिक", "Yearly": "वार्षिक", "Billing & Taxes": "बिलिंग आणि कर", "Business Details": "व्यवसाय तपशील", "Security": "सुरक्षा", "Security & Kitchen": "सुरक्षा आणि किचन", "Manage Chef Mode and Admin PIN": "शेफ मोड आणि अ‍ॅडमिन पिन व्यवस्थापित करा", "Ratings & Reviews": "रेटिंग आणि पुनरावलोकने", "Logout": "लॉग आउट", "Logout?": "लॉग आउट करायचे?", "Are you sure you want to logout?": "तुम्हाला खात्रीने लॉग आउट करायचे आहे का?", "Are you sure you want to logout of your account?": "तुम्हाला खात्रीने तुमच्या खात्यातून लॉग आउट करायचे आहे का?", "Yes, Logout": "होय, लॉग आउट करा", "ACTIVE": "सक्रिय", "INACTIVE": "निष्क्रिय", "EXPIRED": "मुदत संपली", "Valid until": "वैधता", "days remaining": "दिवस शिल्लक", "Expires today": "आज मुदत संपते", "Refer & Get 1 Month Free": "रेफर करा आणि 1 महिना मोफत मिळवा", "Manual renewal only · No auto-debit": "फक्त मॅन्युअल नूतनीकरण · ऑटो-डेबिट नाही", "Processing...": "प्रक्रिया सुरू आहे...", "Renew": "नूतनीकरण करा", "Activate": "सक्रिय करा", "SERVON PLAN": "सर्व्हॉन प्लॅन",

    "AI Business Summary": "AI व्यवसाय सारांश", "Revenue": "कमाई", "Profit": "नफा", "Avg Order Value": "सरासरी ऑर्डर मूल्य", "Best Seller": "सर्वाधिक विकला जाणारा पदार्थ", "Needs Attention": "लक्ष देणे आवश्यक", "Peak Hours": "गर्दीची वेळ", "Customer Feedback": "ग्राहक अभिप्राय", "Recommendations": "सूचना", "Today's Focus": "आजचे लक्ष", "Hour": "तास", "No revenue generated today.": "आज कोणतीही कमाई झाली नाही.", "Profit remains at zero.": "नफा शून्यावर आहे.", "Zero orders recorded today.": "आज एकही ऑर्डर नोंदली नाही.", "Average order value is not applicable.": "सरासरी ऑर्डर मूल्य लागू नाही.", "No best sellers identified yet.": "अजून सर्वाधिक विकला जाणारा पदार्थ नाही.", "Need to encourage more orders.": "अधिक ऑर्डरसाठी ग्राहकांना प्रोत्साहित करा.", "No peak hours identified yet.": "अजून गर्दीची वेळ आढळली नाही.", "No customer feedback received.": "ग्राहकांचा अभिप्राय मिळाला नाही.", "Promote menu items to attract orders.": "ऑर्डर वाढवण्यासाठी मेनूमधील पदार्थ प्रमोट करा.", "Engage customers via social media.": "सोशल मीडियावर ग्राहकांशी जोडा.", "Consider discounts to boost sales.": "विक्री वाढवण्यासाठी सवलतीचा विचार करा.",

    // ── Dashboard: notifications / alerts / toasts ──────────────────────
    "unread": "न वाचलेले", "No notifications yet": "अजून कोणतीही सूचना नाही", "You'll see updates here as they come in": "नवीन सूचना इथे दिसतील", "Trial Reminders": "ट्रायल स्मरणपत्रे", "AI Alerts": "AI सूचना", "Load older notifications": "जुन्या सूचना दाखवा", "New Order": "नवीन ऑर्डर", "Just now": "आत्ताच",
    "Your free trial has expired!": "तुमची मोफत ट्रायल संपली आहे!", "Subscribe": "सदस्यता घ्या",
    "Today": "आज", "Yesterday": "काल",

    // ── Alerts / dialogs (ProfileScreen) ────────────────────────────────
    "Saved!": "जतन झाले!", "Your profile has been updated.": "तुमची प्रोफाइल अद्ययावत झाली आहे.", "Error": "त्रुटी", "Update failed": "अद्ययावत करणे अयशस्वी झाले", "Permission required": "परवानगी आवश्यक आहे", "Please allow photo library access to upload a logo.": "लोगो अपलोड करण्यासाठी फोटो लायब्ररीत प्रवेशाची परवानगी द्या.", "Success": "यशस्वी", "Logo updated!": "लोगो अद्ययावत झाला!", "Logo upload failed": "लोगो अपलोड करणे अयशस्वी झाले", "Hold on!": "थांबा!", "You must set an Admin PIN below before turning on Chef Mode.": "शेफ मोड सुरू करण्यापूर्वी खाली अ‍ॅडमिन पिन सेट करणे आवश्यक आहे.", "Enter Chef Mode?": "शेफ मोडमध्ये जायचे का?", "The app will hide all revenue, analytics, and billing until unlocked with your PIN.": "पिन टाकून अनलॉक करेपर्यंत अ‍ॅप सर्व कमाई, विश्लेषण आणि बिलिंग लपवेल.", "Entering Chef Mode will hide revenue and billing from view. You can unlock it anytime with your Admin PIN.": "शेफ मोडमध्ये गेल्यास कमाई आणि बिलिंग लपवले जाईल. तुम्ही कधीही तुमच्या अ‍ॅडमिन पिनने ते अनलॉक करू शकता.", "Open": "उघडा", "Verification failed.": "पडताळणी अयशस्वी झाली.", "Could not load payment gateway.": "पेमेंट गेटवे लोड होऊ शकला नाही.", "Unable to start payment.": "पेमेंट सुरू करता आले नाही.", "Payment Error": "पेमेंट त्रुटी", "Payment was cancelled or failed.": "पेमेंट रद्द झाले किंवा अयशस्वी झाले.",
    "Invalid": "अवैध", "PIN must be exactly 4 digits": "पिन बरोबर 4 अंकी असावी", "Failed to update PIN": "पिन अद्ययावत करणे अयशस्वी झाले", "Security PIN updated successfully!": "सुरक्षा पिन यशस्वीरित्या अद्ययावत झाली!",

    // ── ProfileScreen: sections / fields ─────────────────────────────────
    "Manage your plan and billing.": "तुमचा प्लॅन आणि बिलिंग व्यवस्थापित करा.", "Update your restaurant information": "तुमच्या रेस्टॉरंटची माहिती अद्ययावत करा", "Configure your GST and tax settings": "तुमचे GST आणि कर सेटिंग्ज सेट करा", "Tax Setup": "कर सेटअप", "Enter your GSTIN and tax percentages to have them automatically applied on bills and invoices.": "बिल आणि पावत्यांवर आपोआप लागू होण्यासाठी तुमचा GSTIN आणि कराची टक्केवारी टाका.",
    "Basic Details": "मूलभूत तपशील", "Chef Mode": "शेफ मोड", "Hides revenue, analytics & billing. Unlock with Admin PIN.": "कमाई, विश्लेषण आणि बिलिंग लपवते. अ‍ॅडमिन पिनने अनलॉक करा.", "Open Chef Mode": "शेफ मोड सुरू करा", "Hides revenue & billing. Unlock with Admin PIN.": "कमाई आणि बिलिंग लपवते. अ‍ॅडमिन पिनने अनलॉक करा.", "Unlock": "अनलॉक करा", "Chef Mode Active": "शेफ मोड सुरू आहे", "Revenue and billing are hidden from view.": "कमाई आणि बिलिंग लपवलेले आहे.", "Revenue and billing are hidden.": "कमाई आणि बिलिंग लपवलेले आहे.",
    "Admin PIN": "अ‍ॅडमिन पिन", "4-digit PIN used to unlock Chef Mode.": "शेफ मोड अनलॉक करण्यासाठी वापरला जाणारा 4-अंकी पिन.", "Update PIN": "पिन अद्ययावत करा",
    "Unsaved": "जतन केलेले नाही", "Unsaved changes": "न जतन केलेले बदल", "You have unsaved changes": "तुमचे काही बदल जतन झालेले नाहीत", "Discard": "रद्द करा", "Save Changes": "बदल जतन करा",
    "Contact Support": "मदतीशी संपर्क साधा", "View Ratings & Reviews": "रेटिंग आणि पुनरावलोकने पहा",
    "You're All Set!": "सर्व काही तयार आहे!", "Payment received. Your Servon subscription is now active.": "पेमेंट मिळाले. तुमची सर्व्हॉन सदस्यता आता सक्रिय आहे.", "Continue to Dashboard": "डॅशबोर्डवर जा",

    "GSTIN Number": "GSTIN क्रमांक", "Enter GSTIN (optional)": "GSTIN टाका (ऐच्छिक)", "CGST %": "CGST %", "SGST %": "SGST %", "e.g. 9": "उदा. 9",
    "Business Name": "व्यवसायाचे नाव", "e.g. Spice Garden": "उदा. स्पाइस गार्डन", "Owner Name": "मालकाचे नाव", "Your full name": "तुमचे पूर्ण नाव", "Phone": "फोन", "10-digit number": "10-अंकी क्रमांक", "Email": "ईमेल", "Description": "वर्णन", "Short description": "छोटे वर्णन", "Address": "पत्ता", "Street address": "रस्त्याचा पत्ता", "City": "शहर", "e.g. Mumbai": "उदा. मुंबई", "State": "राज्य", "e.g. Maharashtra": "उदा. महाराष्ट्र", "Pincode": "पिनकोड", "6-digit pincode": "6-अंकी पिनकोड", "locked": "लॉक केलेले",

    // ── Orders screen ────────────────────────────────────────────────────
    "EDITABLE": "बदलण्यायोग्य", "CONFIRMED": "पुष्टी झाली", "PREPARING": "तयार होत आहे", "SERVED": "सर्व्ह केले", "TABLE ACTIVE": "टेबल चालू", "PAID": "भरले", "PREVIOUS": "मागील", "Table": "टेबल", "Reprint": "पुन्हा प्रिंट करा", "Ordered at:": "ऑर्डरची वेळ:", "Subtotal:": "उपएकूण:",

    // ── Analytics / Expenses ─────────────────────────────────────────────
    "Expenses": "खर्च", "Financial Summary": "आर्थिक सारांश", "TOTAL REVENUE": "एकूण कमाई", "ACCUMULATED EXPENSES": "जमा झालेला खर्च", "NET OPERATION PROFIT": "निव्वळ नफा", "Filter Horizon": "कालावधी निवडा", "Sales": "विक्री", "Daily": "दैनिक", "Weekly": "साप्ताहिक", "Monthly": "मासिक", "PDF": "PDF", "CSV": "CSV", "Records": "नोंदी", "LOG EXPENSE": "खर्च नोंदवा", "Log System Expense": "खर्च नोंदवा", "EXPENSE CATEGORY": "खर्चाची श्रेणी", "VALUATION AMOUNT (INR)": "रक्कम (₹)", "TRANSACTION MEMO / NOTE": "टीप / तपशील", "Provide transaction contexts...": "व्यवहाराबद्दल टीप लिहा...", "RECORD POST DATE": "नोंदीची तारीख", "TODAY": "आज", "SUPPORTING INVOICE SLIP (OPTIONAL)": "बिल / पावती (ऐच्छिक)", "ATTACH INVOICE RECEIPT": "पावती जोडा", "Click to deploy visual validation file": "पावतीचा फोटो अपलोड करण्यासाठी टॅप करा", "Dismiss": "रद्द करा", "Confirm Entry": "नोंद जतन करा", "Export PDF Document": "PDF डाउनलोड करा", "Extract CSV Spreadsheet": "CSV डाउनलोड करा", "CHOOSE PERIOD TIME RANGE": "कालावधी निवडा", "Report Extraction Hub": "अहवाल डाउनलोड करा", "Export authenticated data ledgers": "तुमचा डेटा डाउनलोड करा", "7 Days": "7 दिवस", "30 Days": "30 दिवस", "90 Days": "90 दिवस",
    "Utilities": "वीज-पाणी बिल", "Power, water & utility charges": "वीज, पाणी आणि इतर बिल", "Payroll": "पगार", "Wages, salaries & advances": "पगार आणि आगाऊ रक्कम", "Procurement": "खरेदी", "Raw materials & supplies": "कच्चा माल आणि साहित्य", "Maintenance": "देखभाल", "Equipment & repair costs": "उपकरणे आणि दुरुस्ती खर्च", "Waste": "वाया गेलेले", "Expired or wasted items": "खराब झालेले किंवा वाया गेलेले पदार्थ", "Other": "इतर", "Miscellaneous expenses": "इतर खर्च",

    // ── AI Business Advisor ──────────────────────────────────────────────
    "AI Business Advisor": "AI व्यवसाय सल्लागार", "Ask anything about your business": "तुमच्या व्यवसायाबद्दल काहीही विचारा", "Ask anything about your business...": "तुमच्या व्यवसायाबद्दल काहीही विचारा...", "Chat": "चॅट", "Voice": "व्हॉइस", "Voice AI Business Advisor": "व्हॉइस AI व्यवसाय सल्लागार", "Hold to Talk": "बोलण्यासाठी दाबून ठेवा", "Hold to talk · automatically stops after 45 seconds": "बोलण्यासाठी दाबून ठेवा · 45 सेकंदांनी आपोआप थांबेल", "The spoken reply is AI-generated.": "बोलके उत्तर AI ने तयार केले आहे.", "History": "इतिहास", "No questions yet": "अजून कोणताही प्रश्न नाही", "SUGGESTED QUESTIONS": "सुचवलेले प्रश्न", "View Full Insights": "सर्व माहिती पहा",
// ── Tables / Rooms / misc (finish) ───────────────────────────────────
    "Room": "रूम", "Guests": "पाहुणे", "Occupied": "व्यस्त", "Download QR": "QR डाउनलोड करा",
    "New Table": "नवीन टेबल", "Table Name or Number": "टेबल नाव किंवा क्रमांक", "Confirm & Create": "पुष्टी करा आणि तयार करा", "Delete Table?": "टेबल हटवायची?", "Are you sure?": "तुम्हाला खात्री आहे?",
    "No tables added": "कोणतीही टेबल जोडलेली नाही", "Add tables to generate QR codes for your customers to scan and order.": "ग्राहकांना स्कॅन करून ऑर्डर देण्यासाठी QR कोड तयार करण्यासाठी टेबल जोडा.", "Create Your First Table": "तुमची पहिली टेबल तयार करा",
    "This will permanently remove the table and its QR code. This action cannot be undone.": "हे टेबल आणि त्याचा QR कोड कायमचे हटवेल. ही क्रिया पूर्ववत करता येणार नाही.",
    "Required": "आवश्यक", "Enter a table number": "टेबल क्रमांक टाका", "Failed to add table": "टेबल जोडता आले नाही", "Delete Table": "टेबल हटवा", "Delete failed": "हटवणे अयशस्वी झाले",
    "Download Error": "डाउनलोड त्रुटी", "Could not download QR. Check server connection.": "QR डाउनलोड करता आले नाही. सर्व्हर कनेक्शन तपासा.", "e.g. 05 or T-10": "उदा. 05 किंवा T-10",
    "Failed to load rooms.": "रूम लोड करणे अयशस्वी झाले.", "Please enter a room number.": "कृपया रूम क्रमांक टाका.", "Could not add room.": "रूम जोडता आले नाही.", "Could not save room details.": "रूमचा तपशील जतन करता आले नाही.", "Could not check out room.": "रूम चेक आउट करता आले नाही.", "Could not delete room.": "रूम हटवता आले नाही.",
    "Invalid Counts": "अवैध संख्या", "Counts cannot be negative.": "संख्या ऋण असू शकत नाही.", "Count Mismatch": "संख्येतील तफावत", "Male + Female + Children must equal Total Guests.": "पुरुष + महिला + मुले = एकूण पाहुणे असणे आवश्यक आहे.",
    "Check out the room before deleting it.": "हटवण्यापूर्वी रूम चेक आउट करा.", "Delete Room": "रूम हटवा", "Check out Room": "रूम चेक आउट करा", "added.": "जोडले.", "updated.": "अद्यतनित केले.", "Edit Occupancy": "व्यापणी बदला", "e.g. 204": "उदा. 204",
    // ── Screens batch (finish coverage) mr ──────────────────────────────
    "High Impact": "उच्च प्रभाव", "Thinking...": "विचार करत आहे...", "Common questions": "सामान्य प्रश्न", "Your Questions": "तुमचे प्रश्न", "Delete Chat?": "चॅट हटवायची?", "Clear All Chats?": "सर्व चॅट हटवायच्या?", "Clear All": "सर्व हटवा",
    "Refining your data...": "तुमचा डेटा रिफाइन होत आहे...", "No sales activity recorded": "कोणतीही विक्री क्रिया नोंदवलेली नाही", "Data compiling...": "डेटा संकलित होत आहे...", "AI Response": "AI उत्तर", "View Full Conversation": "संपूर्ण संभाषण पहा", "No transactions recorded": "कोणत्याही व्यवहारांची नोंद नाही",
    "Sales tracks automatically materialize here as client orders are processed.": "ग्राहक ऑर्डर प्रक्रिया झाल्यावर विक्री नोंदी आपोआप येथे दिसतात.", "Daily incoming operational revenue": "दैनिक येणारे ऑपरेशनल उत्पन्न", "Log clear": "लॉग साफ", "No metrics listed for this horizon window view.": "या अवधीत कोणतेही आकडेवारी नाहीत.", "invoice link": "पावती लिंक", "Inspect": "तपासा", "Replace": "बदला",
    "Loading inventory...": "स्टॉक लोड होत आहे...", "What is this item called?": "या पदार्थाचे नाव काय आहे?", "How do you measure it?": "ते कसे मोजता?", "How much do you have right now?": "तुमच्याकडे सध्या किती आहे?", "Warn me when stock falls below": "स्टॉक खाली गेल्यावर मला सूचित करा", "Save Item": "पदार्थ जतन करा", "How much are you adding?": "किती जोडत आहात?", "Or tap a quick amount": "किंवा द्रुत रक्कम निवडा", "Add to Stock": "स्टॉकमध्ये जोडा", "Yes, Remove": "होय, काढा", "Used per order:": "प्रति ऑर्डर वापर:", "Save This Recipe": "ही कृती जतन करा", "No stock items yet": "अद्याप कोणतेही स्टॉक पदार्थ नाहीत", "No menu items found": "कोणतेही मेनू पदार्थ सापडले नाहीत", "Set up now": "आता सेट करा",
    "Price (₹) *": "किंमत (₹) *", "Category *": "श्रेणी *", "Delete Item?": "पदार्थ हटवायचा?",
    "Total:": "एकूण:", "Active Table": "चालू टेबल", "Bill": "बिल", "Unlock Full Business Suite": "संपूर्ण व्यवसाय संच अनलॉक करा", "Take control of your restaurant with Servon's powerful order management tools.": "सर्व्हॉनच्या शक्तिशाली ऑर्डर व्यवस्थापन साधनांसह तुमच्या रेस्टॉरंटवर नियंत्रण मिळवा.", "Upgrade to Premium": "प्रीमियमवर अपग्रेड करा", "Apply Discount": "सूट लागू करा", "Discount": "सूट", "Payable": "देय", "Apply & Print": "लागू करा आणि प्रिंट करा", "Mark Served": "सर्व्ह केले असे चिन्हांकित करा", "Generating Bill...": "बिल तयार होत आहे...", "Print Final Bill": "अंतिम बिल प्रिंट करा", "Select History Date:": "इतिहास तारीख निवडा:",
    "Enter Chef Mode": "शेफ मोडमध्ये प्रवेश करा", "Servon Plan": "सर्व्हॉन प्लॅन",
    "Your referral code": "तुमचा रेफरल कोड", "Copy": "कॉपी करा", "Successful": "यशस्वी", "Pending": "प्रलंबित", "Rewards earned": "मिळवलेले बक्षिसे", "Progress to next reward": "पुढील बक्षीसापर्यंतची प्रगती", "Referral history": "रेफरल इतिहास", "You haven't referred anyone yet.": "तुम्ही अद्याप कोणालाही रेफर केलेले नाही.", "Referral Program": "रेफरल प्रोग्राम", "Invite & earn": "आमंत्रित करा आणि कमवा", "Share Servon with fellow restaurateurs and grow together.": "सहकारी रेस्टॉरंट मालकांसह सर्व्हॉन शेअर करा आणि एकत्र वाढा.", "2 successful referrals": "2 यशस्वी रेफरल", "1 month Premium free": "1 महिना प्रीमियम मोफत",
    "AI Summary": "AI सारांश", "Avg Rating": "सरासरी रेटिंग", "Total Reviews": "एकूण पुनरावलोकने", "Positive": "सकारात्मक", "Filter by Stars": "ताऱ्यांनुसार फिल्टर करा", "No reviews found for this filter.": "या फिल्टरसाठी कोणतीही पुनरावलोकने नाहीत.", "Try a different star rating or check back later.": "वेगळी स्टार रेटिंग वापरून पहा किंवा नंतर पुन्हा तपासा.", "Dine-in Guest": "डाइन-इन पाहुणा", "No written feedback provided.": "लिखित अभिप्राय दिला नाही.", "Items Ordered": "ऑर्डर केलेले पदार्थ",
    "No guests currently checked in.": "सध्या कोणतेही पाहुणे चेक इन नाहीत.", "Track guest occupancy across rooms": "रूममधील पाहुण्यांची व्यापणी ट्रॅक करा", "No rooms yet": "अद्याप रूम नाहीत", "Tap \"+\" to add your first room.": "तुमची पहिली रूम जोडण्यासाठी \"+\" वर टॅप करा.",
    "Staff member not found": "कर्मचारी सापडला नाही", "MONTHLY": "मासिक", "JOINED": "सामील झाले", "CONTACT DETAILS": "संपर्क तपशील", "Joining Date": "सामील होण्याची तारीख", "Monthly Salary": "मासिक पगार", "CURRENT MONTH PAYMENT": "चालू महिन्याचे पेमेंट", "Amount": "रक्कम", "Date": "तारीख", "Notes": "नोट्स", "Pay Salary": "पगार द्या", "SALARY HISTORY": "पगार इतिहास", "No salary payments recorded": "कोणतेही पगार पेमेंट नोंदवलेले नाही", "Edit Staff": "कर्मचारी बदला", "Full Name": "पूर्ण नाव", "Role": "भूमिका", "Update Staff": "कर्मचारी अद्यतन करा", "Mark as Paid": "पैसे दिले असे चिन्हांकित करा",
    "Pay": "पैसे द्या", "Remove": "काढा", "TOTAL STAFF": "एकूण कर्मचारी", "PENDING": "प्रलंबित", "No results found": "कोणतेही परिणाम सापडले नाहीत", "Clear Search": "शोध साफ करा", "No staff members yet": "अद्याप कर्मचारी नाहीत", "Delete Staff Member": "कर्मचारी हटवा",
    "Help & Support": "मदत आणि समर्थन", "Search for anything": "काहीही शोधा", "No matches found": "काहीही सापडले नाही", "Still stuck?": "अजूनही अडचण?", "Email us at support@servon.cloud": "आम्हाला support@servon.cloud वर ईमेल करा",
    "LIVE": "लाइव्ह",
    // ── Alerts / toasts finish (mr) ─────────────────────────────────────
    "Unable to load analytics. Please try again.": "आकडेवारी लोड करता आले नाही. कृपया पुन्हा प्रयत्न करा.", "Session Expired": "सत्र संपले", "Please log in again and retry the download.": "कृपया पुन्हा लॉग इन करा आणि डाउनलोड पुन्हा करा.", "AI Advisor": "AI सल्लागार", "Open the AI Business Advisor tab for the full breakdown.": "संपूर्ण तपशीलासाठी AI व्यवसाय सल्लागार टॅब उघडा.", "Full item list is available on the Menu screen.": "संपूर्ण पदार्थांची यादी मेनू स्क्रीनवर उपलब्ध आहे.", "Could not get response. Please try again.": "उत्तर मिळू शकले नाही. कृपया पुन्हा प्रयत्न करा.",
    "Delete Expense": "खर्च हटवा", "Could not delete expense. Try again.": "खर्च हटवता आले नाही. पुन्हा प्रयत्न करा.", "No Data": "डेटा नाही", "No expenses to export.": "निर्यात करण्यासाठी खर्च नाहीत.", "Export Error": "निर्यात त्रुटी", "Could not export CSV. Please try again.": "CSV निर्यात करता आले नाही. कृपया पुन्हा प्रयत्न करा.", "Could not generate PDF. Please try again.": "PDF तयार करता आले नाही. कृपया पुन्हा प्रयत्न करा.", "Permission Required": "परवानगी आवश्यक", "Please allow photo library access in Settings.": "सेटिंग्जमध्ये फोटो लायब्ररी प्रवेशाची परवानगी द्या.", "Could not open photo library.": "फोटो लायब्ररी उघडता आले नाही.", "Invalid Amount": "अवैध रक्कम", "Please enter a valid amount greater than 0.": "कृपया 0 पेक्षा जास्त वैध रक्कम टाका.",
    "Item name needed": "पदार्थाचे नाव आवश्यक", "Please type a name for this item, like Tomato or Rice.": "कृपया या पदार्थासाठी नाव टाका, जसे टोमॅटो किंवा तांदूळ.", "Could not save": "जतन करता आले नाही", "Something went wrong. Please try again.": "काहीतरी चूक झाली. कृपया पुन्हा प्रयत्न करा.", "Enter an amount": "रक्कम टाका", "Please enter how much stock you're adding.": "तुम्ही किती स्टॉक जोडत आहात ते टाका.", "Could not restock": "स्टॉक जोडता आले नाही", "Could not delete": "हटवता आले नाही",
    "Name, price, and category are required": "नाव, किंमत आणि श्रेणी आवश्यक आहेत", "Save failed": "जतन अयशस्वी झाले", "Delete Item": "पदार्थ हटवा", "Toggle failed": "टॉगल अयशस्वी झाले", "Delete failed": "हटवणे अयशस्वी झाले",
    "Print Failed": "प्रिंट अयशस्वी झाले", "Could not print the bill.": "बिल प्रिंट करता आले नाही.", "Reprint Failed": "पुन्हा प्रिंट अयशस्वी झाले", "Could not reprint the bill.": "बिल पुन्हा प्रिंट करता आले नाही.", "Invalid": "अवैध", "Please enter a valid discount amount.": "कृपया वैध सूट रक्कम टाका.",
    "Saved!": "जतन केले!", "Your profile has been updated.": "तुमचे प्रोफाइल अद्यतनित केले गेले आहे.", "Update failed": "अद्यतन अयशस्वी झाले", "Permission required": "परवानगी आवश्यक", "Please allow photo library access to upload a logo.": "लोगो अपलोड करण्यासाठी फोटो लायब्ररी प्रवेशाची परवानगी द्या.", "Logo updated!": "लोगो अद्यतनित केला!", "Logo upload failed": "लोगो अपलोड अयशस्वी झाले", "Logout": "लॉग आउट", "Are you sure you want to logout?": "तुम्हाला लॉग आउट करायचे आहे का?", "Could not load payment gateway.": "पेमेंट गेटवे लोड करता आले नाही.", "Verification failed.": "पडताळणी अयशस्वी झाली.", "Unable to start payment.": "पेमेंट सुरू करता आले नाही.", "PIN must be exactly 4 digits": "पिन नक्की 4 अंक असणे आवश्यक आहे", "Security PIN updated successfully!": "सुरक्षा पिन यशस्वीरित्या अद्यतनित केली!", "Failed to update PIN": "पिन अद्यतन अयशस्वी झाले", "Hold on!": "थांबा!", "You must set an Admin PIN below before turning on Chef Mode.": "शेफ मोड चालू करण्यापूर्वी खाली अॅडमिन पिन सेट करणे आवश्यक आहे.",
    "Could not load referral data": "रेफरल डेटा लोड करता आले नाही", "Code copied to clipboard!": "कोड क्लिपबोर्डवर कॉपी केला!", "Code Copied": "कोड कॉपी केला", "Your code": "तुमचा कोड", "has been copied!": "कॉपी केला गेला आहे!", "Cannot Redeem": "रीडीम करता येत नाही", "An error occurred.": "एक त्रुटी आली.",
    "Redeem 1 month free": "1 महिना मोफत रीडीम करा", "available": "उपलब्ध", "Cooldown active": "कूलडाउन चालू", "more needed": "अजून आवश्यक", "you can redeem again on": "तुम्ही पुन्हा रीडीम करू शकता", "rewards available to redeem": "रीडीम करण्यासाठी उपलब्ध बक्षिसे", "more referrals needed": "अजून रेफरल आवश्यक", "Joined": "सामील झाले",
    // ── Placeholders finish (mr) ────────────────────────────────────────
    "Ask about your business...": "तुमच्या व्यवसायाबद्दल विचारा...", "For example: Tomato, Potato, Cold Drink": "उदा. टोमॅटो, बटाटा, कोल्ड ड्रिंक", "For example: 2": "उदा. 2", "e.g. Roasted Papad": "उदा. भाजलेले पापड", "Search by name, role, or phone...": "नाव, भूमिका किंवा फोनने शोधा...", "Search questions, e.g. GST, discount, offline": "प्रश्न शोधा, उदा. GST, सूट, ऑफलाइन", "Optional": "ऐच्छिक", "Full Name *": "पूर्ण नाव *", "Phone *": "फोन *", "Role *": "भूमिका *", "e.g. Rahul Sharma": "उदा. राहुल शर्मा", "e.g. Chef, Waiter": "उदा. शेफ, वेटर", "Provide transaction contexts...": "लेनदेन संदर्भ प्रदान करा...", "Ask anything about your business...": "तुमच्या व्यवसायाबद्दल काहीही विचारा...",
  },
  hi: {
    "Dashboard": "डैशबोर्ड", "Orders": "ऑर्डर", "Menu": "मेनू", "Tables": "टेबल", "Rooms": "रूम", "Analytics": "एनालिटिक्स", "Expenses": "खर्च", "Inventory": "स्टॉक", "Staff": "स्टाफ", "Profile": "प्रोफ़ाइल", "Support": "सहायता", "Reviews": "रिव्यू", "Referrals": "रेफरल", "Manual": "मैन्युअल", "Voice": "वॉइस", "Servon Assistant": "सर्वॉन सहायक", "TABLE": "टेबल", "ADD ITEMS": "आइटम जोड़ें", "Search menu items...": "मेनू आइटम खोजें...", "Type a dish name to search your menu.": "मेनू में खोजने के लिए व्यंजन का नाम लिखें।", "Speak your order or room details": "अपना ऑर्डर या रूम का विवरण बोलें", "Listening…": "सुन रहा है…", "Understanding…": "समझ रहा है…", "Start Recording": "रिकॉर्डिंग शुरू करें", "Stop": "रोकें",
    "Save": "सेव करें", "Cancel": "रद्द करें", "Delete": "हटाएँ", "Edit": "बदलें", "Close": "बंद करें", "Search": "खोजें", "Loading...": "लोड हो रहा है...", "Available": "उपलब्ध", "Not Available": "उपलब्ध नहीं", "Accept": "स्वीकारें", "Reject": "अस्वीकार करें", "Serve": "परोसें", "Print": "प्रिंट करें", "Back": "वापस", "Continue": "जारी रखें", "Confirm": "पुष्टि करें",
    "Add Item": "आइटम जोड़ें", "Add Table": "टेबल जोड़ें", "Add Room": "रूम जोड़ें", "Add Stock": "स्टॉक जोड़ें", "Add New Stock Item": "नया स्टॉक आइटम जोड़ें", "Create Order": "ऑर्डर बनाएं", "Room Management": "रूम प्रबंधन", "Staff Management": "स्टाफ प्रबंधन", "AI Business Advisor": "AI बिज़नेस सलाहकार", "Live Orders": "चालू ऑर्डर", "Notifications": "सूचनाएं", "Subtotal": "उप-योग", "Grand Total": "कुल राशि", "Total Amount": "कुल राशि", "Price": "कीमत", "Quantity": "मात्रा", "Category": "श्रेणी", "Item Name *": "आइटम का नाम *", "Item Name": "आइटम का नाम", "Room Number": "रूम नंबर", "Total Guests": "कुल मेहमान", "Male": "पुरुष", "Female": "महिला", "Children": "बच्चे", "Check In": "चेक इन", "Check Out": "चेक आउट", "Low Stock": "कम स्टॉक", "Yes, Delete": "हां, हटाएं", "Done": "हो गया", "Thali": "थाली",
    "Good morning": "सुप्रभात", "Good afternoon": "नमस्कार", "Good evening": "शुभ संध्या", "Good morning 👋": "सुप्रभात 👋", "Refresh": "रीफ्रेश", "Orders Today": "आज के ऑर्डर", "Revenue Today": "आज की कमाई", "Active Tables": "चालू टेबल", "Top Item": "लोकप्रिय आइटम", "No active orders right now": "अभी कोई चालू ऑर्डर नहीं है", "Waiting for customers to scan QR": "ग्राहकों के QR स्कैन करने की प्रतीक्षा है", "Generate Summary": "सारांश बनाएं", "Sales Overview": "बिक्री का सार", "Top Items": "लोकप्रिय आइटम", "View all": "सभी देखें", "Day": "दिन", "Week": "हफ्ता", "Month": "महीना", "Performance Overview": "प्रदर्शन सार", "Total Sales": "कुल बिक्री", "Avg. Order Value": "औसत ऑर्डर मूल्य", "Tables Occupied": "व्यस्त टेबल", "vs yesterday": "कल की तुलना में", "Live": "चालू", "+ Add Item": "+ आइटम जोड़ें",
    "All": "सभी", "Starters": "स्टार्टर्स", "Main Course": "मुख्य व्यंजन", "Breads": "रोटी", "Rice & Biryani": "चावल और बिरयानी", "Desserts": "मिठाई", "Beverages": "पेय", "Soups": "सूप", "Salads": "सलाद", "Snacks": "नाश्ता", "Specials": "विशेष", "Your menu is empty": "आपका मेनू खाली है", "Add your first dish and let customers start ordering in minutes.": "अपना पहला व्यंजन जोड़ें और ग्राहकों को ऑर्डर करने दें।", "Add Your First Item": "अपना पहला आइटम जोड़ें", "Edit Item": "आइटम बदलें", "This is a Thali / Combo": "यह थाली / कॉम्बो है", "Bundle multiple items under one price": "एक कीमत में कई आइटम जोड़ें", "Included Items": "शामिल आइटम", "Add Extra (Manual)": "अतिरिक्त आइटम जोड़ें", "Item Image": "आइटम फोटो", "Tap to upload": "अपलोड करने के लिए टैप करें", "Pick Thali Items": "थाली के आइटम चुनें",

    "Subscription": "सदस्यता", "Manage your plan and billing": "अपना प्लान और बिलिंग संभालें", "Choose Your Plan": "अपना प्लान चुनें", "Current Plan": "मौजूदा प्लान", "Best Value": "सबसे बेहतर", "⭐ Best Value": "⭐ सबसे बेहतर", "Monthly": "मासिक", "Quarterly": "त्रैमासिक", "Yearly": "वार्षिक", "Billing & Taxes": "बिलिंग और टैक्स", "Business Details": "व्यवसाय विवरण", "Security": "सुरक्षा", "Security & Kitchen": "सुरक्षा और किचन", "Manage Chef Mode and Admin PIN": "शेफ मोड और एडमिन पिन प्रबंधित करें", "Ratings & Reviews": "रेटिंग और रिव्यू", "Logout": "लॉग आउट", "Logout?": "लॉग आउट करें?", "Are you sure you want to logout?": "क्या आप वाकई लॉग आउट करना चाहते हैं?", "Are you sure you want to logout of your account?": "क्या आप वाकई अपने खाते से लॉग आउट करना चाहते हैं?", "Yes, Logout": "हां, लॉग आउट करें", "ACTIVE": "सक्रिय", "INACTIVE": "निष्क्रिय", "EXPIRED": "समाप्त", "Valid until": "मान्य तक", "days remaining": "दिन बाकी", "Expires today": "आज समाप्त हो रहा है", "Refer & Get 1 Month Free": "रेफर करें और 1 महीना मुफ्त पाएं", "Manual renewal only · No auto-debit": "केवल मैन्युअल नवीनीकरण · ऑटो-डेबिट नहीं", "Processing...": "प्रोसेस हो रहा है...", "Renew": "नवीनीकरण करें", "Activate": "सक्रिय करें", "SERVON PLAN": "सर्वॉन प्लान",

    "AI Business Summary": "AI बिज़नेस सारांश", "Revenue": "कमाई", "Profit": "मुनाफ़ा", "Avg Order Value": "औसत ऑर्डर मूल्य", "Best Seller": "सबसे अधिक बिकने वाला", "Needs Attention": "ध्यान दें", "Peak Hours": "व्यस्त समय", "Customer Feedback": "ग्राहक प्रतिक्रिया", "Recommendations": "सुझाव", "Today's Focus": "आज का फोकस", "Hour": "घंटा", "No revenue generated today.": "आज कोई कमाई नहीं हुई।", "Profit remains at zero.": "मुनाफ़ा शून्य है।", "Zero orders recorded today.": "आज कोई ऑर्डर दर्ज नहीं हुआ।", "Average order value is not applicable.": "औसत ऑर्डर मूल्य लागू नहीं है।", "No best sellers identified yet.": "अभी कोई सबसे अधिक बिकने वाला आइटम नहीं है।", "Need to encourage more orders.": "अधिक ऑर्डर के लिए ग्राहकों को प्रोत्साहित करें।", "No peak hours identified yet.": "अभी व्यस्त समय नहीं मिला है।", "No customer feedback received.": "कोई ग्राहक प्रतिक्रिया नहीं मिली।", "Promote menu items to attract orders.": "ऑर्डर बढ़ाने के लिए मेनू आइटम प्रमोट करें।", "Engage customers via social media.": "सोशल मीडिया पर ग्राहकों से जुड़ें।", "Consider discounts to boost sales.": "बिक्री बढ़ाने के लिए छूट पर विचार करें।",

    "unread": "अपठित", "No notifications yet": "अभी तक कोई सूचना नहीं", "You'll see updates here as they come in": "नई सूचनाएं यहां दिखेंगी", "Trial Reminders": "ट्रायल रिमाइंडर", "AI Alerts": "AI सूचनाएं", "Load older notifications": "पुरानी सूचनाएं दिखाएं", "New Order": "नया ऑर्डर", "Just now": "अभी अभी",
    "Your free trial has expired!": "आपकी मुफ्त ट्रायल समाप्त हो गई है!", "Subscribe": "सदस्यता लें",
    "Today": "आज", "Yesterday": "कल",

    "Saved!": "सेव हो गया!", "Your profile has been updated.": "आपकी प्रोफ़ाइल अपडेट हो गई है।", "Error": "त्रुटि", "Update failed": "अपडेट करना विफल हुआ", "Permission required": "अनुमति आवश्यक है", "Please allow photo library access to upload a logo.": "लोगो अपलोड करने के लिए फोटो लाइब्रेरी की अनुमति दें।", "Success": "सफल", "Logo updated!": "लोगो अपडेट हो गया!", "Logo upload failed": "लोगो अपलोड करना विफल हुआ", "Hold on!": "रुकिए!", "You must set an Admin PIN below before turning on Chef Mode.": "शेफ मोड चालू करने से पहले नीचे एडमिन पिन सेट करना जरूरी है।", "Enter Chef Mode?": "शेफ मोड में जाएं?", "The app will hide all revenue, analytics, and billing until unlocked with your PIN.": "पिन से अनलॉक होने तक ऐप सारी कमाई, एनालिटिक्स और बिलिंग छुपा देगा।", "Entering Chef Mode will hide revenue and billing from view. You can unlock it anytime with your Admin PIN.": "शेफ मोड में जाने पर कमाई और बिलिंग छुप जाएगी। आप कभी भी अपने एडमिन पिन से इसे अनलॉक कर सकते हैं।", "Open": "खोलें", "Verification failed.": "सत्यापन विफल हुआ।", "Could not load payment gateway.": "पेमेंट गेटवे लोड नहीं हो सका।", "Unable to start payment.": "पेमेंट शुरू नहीं हो सका।", "Payment Error": "पेमेंट त्रुटि", "Payment was cancelled or failed.": "पेमेंट रद्द हुआ या विफल हुआ।",
    "Invalid": "अमान्य", "PIN must be exactly 4 digits": "पिन बिल्कुल 4 अंकों का होना चाहिए", "Failed to update PIN": "पिन अपडेट करना विफल हुआ", "Security PIN updated successfully!": "सुरक्षा पिन सफलतापूर्वक अपडेट हो गई!",

    "Manage your plan and billing.": "अपना प्लान और बिलिंग प्रबंधित करें।", "Update your restaurant information": "अपने रेस्टोरेंट की जानकारी अपडेट करें", "Configure your GST and tax settings": "अपनी GST और टैक्स सेटिंग्स सेट करें", "Tax Setup": "टैक्स सेटअप", "Enter your GSTIN and tax percentages to have them automatically applied on bills and invoices.": "बिल और चालान पर अपने आप लागू होने के लिए अपना GSTIN और टैक्स प्रतिशत डालें।",
    "Basic Details": "बुनियादी विवरण", "Chef Mode": "शेफ मोड", "Hides revenue, analytics & billing. Unlock with Admin PIN.": "कमाई, एनालिटिक्स और बिलिंग छुपाता है। एडमिन पिन से अनलॉक करें।", "Open Chef Mode": "शेफ मोड चालू करें", "Hides revenue & billing. Unlock with Admin PIN.": "कमाई और बिलिंग छुपाता है। एडमिन पिन से अनलॉक करें।", "Unlock": "अनलॉक करें", "Chef Mode Active": "शेफ मोड चालू है", "Revenue and billing are hidden from view.": "कमाई और बिलिंग छुपाई गई है।", "Revenue and billing are hidden.": "कमाई और बिलिंग छुपाई गई है।",
    "Admin PIN": "एडमिन पिन", "4-digit PIN used to unlock Chef Mode.": "शेफ मोड अनलॉक करने के लिए इस्तेमाल होने वाला 4-अंकों का पिन।", "Update PIN": "पिन अपडेट करें",
    "Unsaved": "सेव नहीं किया", "Unsaved changes": "बिना सेव किए बदलाव", "You have unsaved changes": "आपके कुछ बदलाव सेव नहीं हुए हैं", "Discard": "रद्द करें", "Save Changes": "बदलाव सेव करें",
    "Contact Support": "सहायता से संपर्क करें", "View Ratings & Reviews": "रेटिंग और रिव्यू देखें",
    "You're All Set!": "सब कुछ तैयार है!", "Payment received. Your Servon subscription is now active.": "पेमेंट मिल गया। आपकी सर्वॉन सदस्यता अब सक्रिय है।", "Continue to Dashboard": "डैशबोर्ड पर जाएं",

    "GSTIN Number": "GSTIN नंबर", "Enter GSTIN (optional)": "GSTIN डालें (वैकल्पिक)", "CGST %": "CGST %", "SGST %": "SGST %", "e.g. 9": "उदा. 9",
    "Business Name": "व्यवसाय का नाम", "e.g. Spice Garden": "उदा. स्पाइस गार्डन", "Owner Name": "मालिक का नाम", "Your full name": "आपका पूरा नाम", "Phone": "फोन", "10-digit number": "10-अंकों का नंबर", "Email": "ईमेल", "Description": "विवरण", "Short description": "संक्षिप्त विवरण", "Address": "पता", "Street address": "गली का पता", "City": "शहर", "e.g. Mumbai": "उदा. मुंबई", "State": "राज्य", "e.g. Maharashtra": "उदा. महाराष्ट्र", "Pincode": "पिनकोड", "6-digit pincode": "6-अंकों का पिनकोड", "locked": "लॉक किया गया",
// ── Tables / Rooms / misc (finish) ───────────────────────────────────
    "Room": "रूम", "Guests": "मेहमान", "Occupied": "कब्जे में", "Download QR": "QR डाउनलोड करें",
    "New Table": "नई टेबल", "Table Name or Number": "टेबल नाम या नंबर", "Confirm & Create": "पुष्टि करें और बनाएं", "Delete Table?": "टेबल हटाएं?", "Are you sure?": "क्या आपको यकीन है?",
    "No tables added": "कोई टेबल नहीं जोड़ी गई", "Add tables to generate QR codes for your customers to scan and order.": "ग्राहकों द्वारा स्कैन कर ऑर्डर करने के लिए QR कोड बनाने हेतु टेबल जोड़ें।", "Create Your First Table": "अपनी पहली टेबल बनाएं",
    "This will permanently remove the table and its QR code. This action cannot be undone.": "यह टेबल और इसका QR कोड स्थायी रूप से हटा देगा। यह क्रिया पूर्ववत नहीं की जा सकती।",
    "Required": "आवश्यक", "Enter a table number": "टेबल नंबर दर्ज करें", "Failed to add table": "टेबल नहीं जोड़ा जा सका", "Delete Table": "टेबल हटाएं", "Delete failed": "हटाना विफल हुआ",
    "Download Error": "डाउनलोड त्रुटि", "Could not download QR. Check server connection.": "QR डाउनलोड नहीं हुआ। सर्वर कनेक्शन जांचें।", "e.g. 05 or T-10": "उदा. 05 या T-10",
    "Failed to load rooms.": "रूम लोड करना विफल हुआ।", "Please enter a room number.": "कृपया रूम नंबर दर्ज करें।", "Could not add room.": "रूम नहीं जोड़ा जा सका।", "Could not save room details.": "रूम विवरण सेव नहीं हुआ।", "Could not check out room.": "रूम चेक-आउट नहीं हुआ।", "Could not delete room.": "रूम हटाया नहीं जा सका।",
    "Invalid Counts": "अमान्य संख्या", "Counts cannot be negative.": "संख्या नकारात्मक नहीं हो सकती।", "Count Mismatch": "संख्या बेमेल", "Male + Female + Children must equal Total Guests.": "पुरुष + महिला + बच्चे = कुल मेहमान होने चाहिए।",
    "Check out the room before deleting it.": "हटाने से पहले रूम चेक-आउट करें।", "Delete Room": "रूम हटाएं", "Check out Room": "रूम चेक-आउट करें", "added.": "जोड़ा गया।", "updated.": "अपडेट किया गया।", "Edit Occupancy": "कब्जा संपादित करें", "e.g. 204": "उदा. 204",
    // ── Screens batch (finish coverage) hi ──────────────────────────────
    "High Impact": "उच्च प्रभाव", "Thinking...": "सोच रहा है...", "Common questions": "सामान्य प्रश्न", "Your Questions": "आपके प्रश्न", "Delete Chat?": "चैट हटाएं?", "Clear All Chats?": "सभी चैट हटाएं?", "Clear All": "सभी हटाएं",
    "Refining your data...": "आपका डेटा रिफाइन हो रहा है...", "No sales activity recorded": "कोई बिक्री गतिविधि दर्ज नहीं", "Data compiling...": "डेटा संकलित हो रहा है...", "AI Response": "AI जवाब", "View Full Conversation": "पूरी बातचीत देखें", "No transactions recorded": "कोई लेन-देन दर्ज नहीं",
    "Sales tracks automatically materialize here as client orders are processed.": "ग्राहक ऑर्डर प्रोसेस होने पर बिक्री रिकॉर्ड यहाँ अपने आप दिखते हैं।", "Daily incoming operational revenue": "दैनिक परिचालन राजस्व", "Log clear": "लॉग साफ़", "No metrics listed for this horizon window view.": "इस अवधि के लिए कोई मेट्रिक्स नहीं।", "invoice link": "बिल लिंक", "Inspect": "जांचें", "Replace": "बदलें",
    "Loading inventory...": "स्टॉक लोड हो रहा है...", "What is this item called?": "इस आइटम का नाम क्या है?", "How do you measure it?": "इसे कैसे मापेंगे?", "How much do you have right now?": "अभी आपके पास कितना है?", "Warn me when stock falls below": "स्टॉक कम होने पर मुझे सूचित करें", "Save Item": "आइटम सेव करें", "How much are you adding?": "कितना जोड़ रहे हैं?", "Or tap a quick amount": "या त्वरित राशि चुनें", "Add to Stock": "स्टॉक में जोड़ें", "Yes, Remove": "हाँ, हटाएं", "Used per order:": "प्रति ऑर्डर उपयोग:", "Save This Recipe": "यह रेसिपी सेव करें", "No stock items yet": "अभी तक कोई स्टॉक आइटम नहीं", "No menu items found": "कोई मेनू आइटम नहीं मिला", "Set up now": "अभी सेट करें",
    "Price (₹) *": "कीमत (₹) *", "Category *": "श्रेणी *", "Delete Item?": "आइटम हटाएं?",
    "Total:": "कुल:", "Active Table": "चालू टेबल", "Bill": "बिल", "Unlock Full Business Suite": "पूर्ण बिज़नेस सूट अनलॉक करें", "Take control of your restaurant with Servon's powerful order management tools.": "सर्वॉन के शक्तिशाली ऑर्डर प्रबंधन टूल्स के साथ अपने रेस्तरां पर नियंत्रण पाएं।", "Upgrade to Premium": "प्रीमियम पर अपग्रेड करें", "Apply Discount": "छूट लागू करें", "Discount": "छूट", "Payable": "देय", "Apply & Print": "लागू करें और प्रिंट करें", "Mark Served": "परोसा गया चिह्नित करें", "Generating Bill...": "बिल बन रहा है...", "Print Final Bill": "अंतिम बिल प्रिंट करें", "Select History Date:": "इतिहास तिथि चुनें:",
    "Enter Chef Mode": "शेफ मोड में प्रवेश करें", "Servon Plan": "सर्वॉन प्लान",
    "Your referral code": "आपका रेफरल कोड", "Copy": "कॉपी करें", "Successful": "सफल", "Pending": "लंबित", "Rewards earned": "अर्जित पुरस्कार", "Progress to next reward": "अगले पुरस्कार तक प्रगति", "Referral history": "रेफरल इतिहास", "You haven't referred anyone yet.": "आपने अभी तक किसी को रेफर नहीं किया।", "Referral Program": "रेफरल प्रोग्राम", "Invite & earn": "आमंत्रित करें और कमाएं", "Share Servon with fellow restaurateurs and grow together.": "साथी रेस्तरां मालकों के साथ सर्वॉन साझा करें और साथ बढ़ें।", "2 successful referrals": "2 सफल रेफरल", "1 month Premium free": "1 महीना प्रीमियम मुफ़्त",
    "AI Summary": "AI सारांश", "Avg Rating": "औसत रेटिंग", "Total Reviews": "कुल रिव्यू", "Positive": "सकारात्मक", "Filter by Stars": "स्टार्स द्वारा फ़िल्टर करें", "No reviews found for this filter.": "इस फ़िल्टर के लिए कोई रिव्यू नहीं मिला।", "Try a different star rating or check back later.": "अलग स्टार रेटिंग आज़माएं या बाद में फिर देखें।", "Dine-in Guest": "डाइन-इन मेहमान", "No written feedback provided.": "कोई लिखित प्रतिक्रिया नहीं दी गई।", "Items Ordered": "ऑर्डर किए गए आइटम",
    "No guests currently checked in.": "अभी कोई मेहमान चेक-इन नहीं।", "Track guest occupancy across rooms": "रूम में मेहमानों की कब्जा स्थिति ट्रैक करें", "No rooms yet": "अभी तक कोई रूम नहीं", "Tap \"+\" to add your first room.": "अपना पहला रूम जोड़ने के लिए \"+\" पर टैप करें।",
    "Staff member not found": "स्टाफ सदस्य नहीं मिला", "MONTHLY": "मासिक", "JOINED": "जुड़े", "CONTACT DETAILS": "संपर्क विवरण", "Joining Date": "जुड़ने की तिथि", "Monthly Salary": "मासिक वेतन", "CURRENT MONTH PAYMENT": "वर्तमान माह का भुगतान", "Amount": "राशि", "Date": "तिथि", "Notes": "नोट्स", "Pay Salary": "वेतन दें", "SALARY HISTORY": "वेतन इतिहास", "No salary payments recorded": "कोई वेतन भुगतान दर्ज नहीं", "Edit Staff": "स्टाफ संपादित करें", "Full Name": "पूरा नाम", "Role": "भूमिका", "Update Staff": "स्टाफ अपडेट करें", "Mark as Paid": "भुगतान किया चिह्नित करें",
    "Pay": "भुगतान करें", "Remove": "हटाएं", "TOTAL STAFF": "कुल स्टाफ", "PENDING": "लंबित", "No results found": "कोई परिणाम नहीं मिला", "Clear Search": "खोज साफ़ करें", "No staff members yet": "अभी तक कोई स्टाफ नहीं", "Delete Staff Member": "स्टाफ सदस्य हटाएं",
    "Help & Support": "सहायता और समर्थन", "Search for anything": "कुछ भी खोजें", "No matches found": "कोई मेल नहीं मिला", "Still stuck?": "फिर भी अटके हैं?", "Email us at support@servon.cloud": "हमें support@servon.cloud पर ईमेल करें",
    "LIVE": "लाइव",
    // ── Alerts / toasts finish (hi) ─────────────────────────────────────
    "Unable to load analytics. Please try again.": "एनालिटिक्स लोड नहीं हो सका। कृपया फिर प्रयास करें।", "Session Expired": "सत्र समाप्त", "Please log in again and retry the download.": "कृपया फिर लॉग इन करें और डाउनलोड दोबारा करें।", "AI Advisor": "AI सलाहकार", "Open the AI Business Advisor tab for the full breakdown.": "पूरी जानकारी के लिए AI बिज़नेस सलाहकार टैब खोलें।", "Full item list is available on the Menu screen.": "पूरी आइटम सूची मेनू स्क्रीन पर उपलब्ध है।", "Could not get response. Please try again.": "जवाब नहीं मिल सका। कृपया फिर प्रयास करें।",
    "Delete Expense": "खर्च हटाएं", "Could not delete expense. Try again.": "खर्च हटाया नहीं जा सका। फिर प्रयास करें।", "No Data": "कोई डेटा नहीं", "No expenses to export.": "निर्यात करने के लिए कोई खर्च नहीं।", "Export Error": "निर्यात त्रुटि", "Could not export CSV. Please try again.": "CSV निर्यात नहीं हुआ। कृपया फिर प्रयास करें।", "Could not generate PDF. Please try again.": "PDF नहीं बन सका। कृपया फिर प्रयास करें।", "Permission Required": "अनुमति आवश्यक", "Please allow photo library access in Settings.": "सेटिंग्स में फोटो लाइब्रेरी की अनुमति दें।", "Could not open photo library.": "फोटो लाइब्रेरी नहीं खुल सकी।", "Invalid Amount": "अमान्य राशि", "Please enter a valid amount greater than 0.": "कृपया 0 से अधिक मान्य राशि दर्ज करें।",
    "Item name needed": "आइटम नाम आवश्यक", "Please type a name for this item, like Tomato or Rice.": "कृपया इस आइटम के लिए नाम लिखें, जैसे टमाटर या चावल।", "Could not save": "सेव नहीं हो सका", "Something went wrong. Please try again.": "कुछ गलत हो गया। कृपया फिर प्रयास करें।", "Enter an amount": "राशि दर्ज करें", "Please enter how much stock you're adding.": "बताएं कि आप कितना स्टॉक जोड़ रहे हैं।", "Could not restock": "स्टॉक नहीं जोड़ा जा सका", "Could not delete": "हटाया नहीं जा सका",
    "Name, price, and category are required": "नाम, कीमत और श्रेणी आवश्यक हैं", "Save failed": "सेव विफल हुआ", "Delete Item": "आइटम हटाएं", "Toggle failed": "टॉगल विफल हुआ", "Delete failed": "हटाना विफल हुआ",
    "Print Failed": "प्रिंट विफल", "Could not print the bill.": "बिल प्रिंट नहीं हो सका।", "Reprint Failed": "फिर प्रिंट विफल", "Could not reprint the bill.": "बिल फिर प्रिंट नहीं हो सका।", "Invalid": "अमान्य", "Please enter a valid discount amount.": "कृपया मान्य छूट राशि दर्ज करें।",
    "Saved!": "सेव हो गया!", "Your profile has been updated.": "आपकी प्रोफ़ाइल अपडेट हो गई है।", "Update failed": "अपडेट विफल हुआ", "Permission required": "अनुमति आवश्यक", "Please allow photo library access to upload a logo.": "लोगो अपलोड करने के लिए फोटो लाइब्रेरी की अनुमति दें।", "Logo updated!": "लोगो अपडेट हो गया!", "Logo upload failed": "लोगो अपलोड विफल हुआ", "Logout": "लॉग आउट", "Are you sure you want to logout?": "क्या आप लॉग आउट करना चाहते हैं?", "Could not load payment gateway.": "पेमेंट गेटवे लोड नहीं हो सका।", "Verification failed.": "सत्यापन विफल हुआ।", "Unable to start payment.": "पेमेंट शुरू नहीं हो सका।", "PIN must be exactly 4 digits": "पिन बिल्कुल 4 अंकों का होना चाहिए", "Security PIN updated successfully!": "सुरक्षा पिन सफलतापूर्वक अपडेट हुई!", "Failed to update PIN": "पिन अपडेट विफल हुआ", "Hold on!": "रुको!", "You must set an Admin PIN below before turning on Chef Mode.": "शेफ मोड चालू करने से पहले नीचे एडमिन पिन सेट करना आवश्यक है।",
    "Could not load referral data": "रेफरल डेटा लोड नहीं हो सका", "Code copied to clipboard!": "कोड क्लिपबोर्ड पर कॉपी हो गया!", "Code Copied": "कोड कॉपी हुआ", "Your code": "आपका कोड", "has been copied!": "कॉपी हो गया है!", "Cannot Redeem": "रीडीम नहीं कर सकते", "An error occurred.": "एक त्रुटि हुई।",
    "Redeem 1 month free": "1 महीना मुफ़्त रीडीम करें", "available": "उपलब्ध", "Cooldown active": "कूलडाउन सक्रिय", "more needed": "और चाहिए", "you can redeem again on": "आप फिर रीडीम कर सकते हैं", "rewards available to redeem": "रीडीम करने के लिए उपलब्ध पुरस्कार", "more referrals needed": "और रेफरल चाहिए", "Joined": "जुड़े",
    // ── Placeholders finish (hi) ────────────────────────────────────────
    "Ask about your business...": "अपने व्यवसाय के बारे में पूछें...", "For example: Tomato, Potato, Cold Drink": "उदा. टमाटर, आलू, कोल्ड ड्रिंक", "For example: 2": "उदा. 2", "e.g. Roasted Papad": "उदा. रोस्टेड पापड़", "Search by name, role, or phone...": "नाम, भूमिका या फोन से खोजें...", "Search questions, e.g. GST, discount, offline": "प्रश्न खोजें, उदा. GST, छूट, ऑफलाइन", "Optional": "वैकल्पिक", "Full Name *": "पूरा नाम *", "Phone *": "फोन *", "Role *": "भूमिका *", "e.g. Rahul Sharma": "उदा. राहुल शर्मा", "e.g. Chef, Waiter": "उदा. शेफ, वेटर", "Provide transaction contexts...": "लेन-देन का संदर्भ दें...", "Ask anything about your business...": "अपने व्यवसाय के बारे में कुछ भी पूछें...",

    // ── Orders screen ────────────────────────────────────────────────────
    "EDITABLE": "बदलने योग्य", "CONFIRMED": "पुष्टि हुई", "PREPARING": "तैयार हो रहा है", "SERVED": "परोसा गया", "TABLE ACTIVE": "टेबल चालू", "PAID": "भुगतान हुआ", "PREVIOUS": "पिछले", "Table": "टेबल", "Reprint": "फिर से प्रिंट करें", "Ordered at:": "ऑर्डर का समय:", "Subtotal:": "उप-योग:",

    // ── Analytics / Expenses ─────────────────────────────────────────────
    "Expenses": "खर्च", "Financial Summary": "वित्तीय सारांश", "TOTAL REVENUE": "कुल कमाई", "ACCUMULATED EXPENSES": "कुल खर्च", "NET OPERATION PROFIT": "शुद्ध मुनाफ़ा", "Filter Horizon": "अवधि चुनें", "Sales": "बिक्री", "Daily": "दैनिक", "Weekly": "साप्ताहिक", "Monthly": "मासिक", "PDF": "PDF", "CSV": "CSV", "Records": "रिकॉर्ड", "LOG EXPENSE": "खर्च दर्ज करें", "Log System Expense": "खर्च दर्ज करें", "EXPENSE CATEGORY": "खर्च की श्रेणी", "VALUATION AMOUNT (INR)": "राशि (₹)", "TRANSACTION MEMO / NOTE": "नोट / विवरण", "Provide transaction contexts...": "लेन-देन के बारे में नोट लिखें...", "RECORD POST DATE": "रिकॉर्ड की तारीख", "TODAY": "आज", "SUPPORTING INVOICE SLIP (OPTIONAL)": "बिल / रसीद (वैकल्पिक)", "ATTACH INVOICE RECEIPT": "रसीद जोड़ें", "Click to deploy visual validation file": "रसीद की फोटो अपलोड करने के लिए टैप करें", "Dismiss": "रद्द करें", "Confirm Entry": "एंट्री सेव करें", "Export PDF Document": "PDF डाउनलोड करें", "Extract CSV Spreadsheet": "CSV डाउनलोड करें", "CHOOSE PERIOD TIME RANGE": "अवधि चुनें", "Report Extraction Hub": "रिपोर्ट डाउनलोड करें", "Export authenticated data ledgers": "अपना डेटा डाउनलोड करें", "7 Days": "7 दिन", "30 Days": "30 दिन", "90 Days": "90 दिन",
    "Utilities": "बिजली-पानी बिल", "Power, water & utility charges": "बिजली, पानी और अन्य बिल", "Payroll": "वेतन", "Wages, salaries & advances": "वेतन और एडवांस राशि", "Procurement": "खरीद", "Raw materials & supplies": "कच्चा माल और सामान", "Maintenance": "रखरखाव", "Equipment & repair costs": "उपकरण और मरम्मत खर्च", "Waste": "बर्बाद माल", "Expired or wasted items": "खराब या बर्बाद हुए सामान", "Other": "अन्य", "Miscellaneous expenses": "अन्य खर्च",

    // ── AI Business Advisor ──────────────────────────────────────────────
    "AI Business Advisor": "AI बिज़नेस सलाहकार", "Ask anything about your business": "अपने व्यवसाय के बारे में कुछ भी पूछें", "Ask anything about your business...": "अपने व्यवसाय के बारे में कुछ भी पूछें...", "Chat": "चैट", "Voice": "वॉइस", "Voice AI Business Advisor": "वॉइस AI बिज़नेस सलाहकार", "Hold to Talk": "बोलने के लिए दबाए रखें", "Hold to talk · automatically stops after 45 seconds": "बोलने के लिए दबाए रखें · 45 सेकंड बाद अपने आप रुक जाएगा", "The spoken reply is AI-generated.": "बोला गया जवाब AI द्वारा तैयार किया गया है।", "History": "इतिहास", "No questions yet": "अभी तक कोई सवाल नहीं", "SUGGESTED QUESTIONS": "सुझाए गए सवाल", "View Full Insights": "पूरी जानकारी देखें",
  },
};

export function localizeText(value, language) {
  if (typeof value !== "string" || language === "en") return value;
  const padding = value.match(/^\s*/)?.[0] || "";
  const tail = value.match(/\s*$/)?.[0] || "";
  const core = value.trim();
  const hit = phrases[language]?.[core];
  if (core && !hit && typeof __DEV__ !== "undefined" && __DEV__) {
    // eslint-disable-next-line no-console
    console.warn(`[i18n] missing ${language} phrase: "${core}"`);
  }
  return hit ? `${padding}${hit}${tail}` : value;
}

export default function LocalizedText({ children, ...props }) {
  const { language } = useLocale();
  return <NativeText {...props}>{React.Children.map(children, (child) => localizeText(child, language))}</NativeText>;
}